apiVersion: v1
kind: Service
metadata:
  name: {{ include "apache-ranger.fullname" . }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 6080
  selector:
    app: {{ include "apache-ranger.name" . }}
  {{- if .Values.service.externalIPs }}
  externalIPs:
    {{- toYaml .Values.service.externalIPs | nindent 4 }}
  {{- end }}